### ISSUE TITLE
TA - Duplicate items/categories appearing when multiple permission rules are applied

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#223] opened 2015-09-11 13:39 UTC
When a TA is granted multiple permission rules that provide overlap for a given category, the category's items are duplicated in the TA's view.

E.g., TA is granted "View" access to ALL categories in the Gradebook, but "Grade" access to only 1 category (let's call it "Homework"). When the TA views the GB, they will see all of the items in "Homework" twice. One instance of the "Homework" items are not editable (bc of the "View" permissions), while the other is editable (bc of the "Edit" permissions).

**Comment by steveswinsburg** [comment] 2015-09-14 11:18
Reproducable. The bug is a long standing one in `GradebookService.getViewableAssignmentsForCurrentUser`.

Under the above settings, the assignment list is duplicated.

This is because the checks will satisfy BOTH:
`if (getGradebookPermissionService().getPermissionForUserForAllAssignment(gradebook.getId(), userUid)) {
     assignmentsToReturn = getAssignments(gradebookUid);
 }
`
_and_ the following iteration of assignments within categories, which then adds more assignments to the `assignmentsToReturn` variable. 

This is proven by stepping through this method with a debugger from access of both Gradebook and GradebookNG, and a watch on `assignmentsToReturn`. If there are two assignments, it will end up with 4. 
Gradebook must be then removing duplicates.

**Comment by steveswinsburg** [comment] 2015-09-14 12:18
Bug fixed in https://jira.sakaiproject.org/browse/SAK-29890  and PR in https://github.com/sakaiproject/sakai/pull/1069

**Comment by steveswinsburg** [comment] 2015-09-28 12:31
Fixed in GradebookService, this should be gone in GBNG now.

**Comment by kyleblythe** [comment] 2015-10-01 14:26
The duplicate category items are no longer appearing. I wonder if this somehow is related to #251 , however.

**Comment by steveswinsburg** [comment] 2015-10-01 20:55
Indirectly related to #211.

**Comment by steveswinsburg** [comment] 2015-10-01 20:56
Three tickets referencing same feature so I'm going to close this one off since the categories are sorted out now.

**Closed as completed by steveswinsburg** 2015-10-01 20:56 UTC
Labels: bug, priority
