### ISSUE TITLE
Student grade summary enhancements

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#186] opened 2015-08-19 06:38 UTC
As per minutes from the call:
- Get rid of item weights in weight column, but show the category weight
- Status icons should show up just to the right of the item
- Condense to 70% width
- Keep “Next Student/Previous Student” visible and scroll inside of it
- Pull Course Grade value closer to the label
- normal lightbox treatment when in “Grade Summary,” Sexy Shower Glass, when in “Student Review Mode”.

**Comment by payten** [comment] 2015-08-19 06:41
All delivered in PR #183. 

Re: " Sexy Shower Glass" -- I have a lovely, even sexy, solution that works nicely in Firefox, Chrome and Safari (https://github.com/steveswinsburg/gradebookNG/compare/master...payten:bringing-sexy-back).  Unfortunately IE versions 9-11 don’t support the CSS blur filter, and with that, the sexiness is sunk.  As such, we'll retain the opaque dark mask when the student view is selected.

**Comment by kyleblythe** [comment] 2015-08-20 18:58
Hi @payten ,

This is looking great. The page width, layout, iconography all look great. A few things I noticed:
- The weighting for the category is displaying in parentheses next to the category name, while the current subtotal is displaying under the "Grades" column: http://www.screencast.com/t/0kkqcezuQs. Wondering if this might be confusing. Would it make more sense to reintroduce a "Weight" column, to the left of "Grades," which would only show the category weighting, not the item weighting?
- In your comment re: the sexy shower glass, are we saying that, because the blur does does not work in IE 9-11, we should stick with the existing dark mask? I know that IE's been replaced in Windows 10 (with Edge?), and I'm wondering if the CSS would be supported there. Since IE's always been a bit of a problem child, is it possible to use the blur for browsers that support it, and default back to the dark mask for the ones that don't?
- As referenced in PR #66 , is it possible to introduce an additional confirmation lightbox window that opens on top of the "Student Review" mode when you try to exit out, letting you know that you're about to surface other students' grades?

**Comment by payten** [comment] 2015-08-20 23:14
Re: weighting - yep can pull that column back in.  And that column would be blank for grade item rows?

Re: shower glass - I've created an issue to investigate a mechanism to target CSS to IE9-11 #193 and therefore support a reasonable fallback.  Unfortunately, in implementing Edge for IE10 and 11, they decided to drop support for the old IE filters (including a blur feature) but are yet to provide a replacement (http://www.broken-links.com/2013/11/20/cross-browser-filters-css-svg/) - IE continues to frustrate web developers everywhere!  Btw, this is how it would look in Chrome:
<img width="1388" alt="screen shot 2015-08-21 at 8 58 41 am" src="https://cloud.githubusercontent.com/assets/608337/9397729/fbabe9da-47e2-11e5-9c8b-53fac3eac923.png">
- re: close confirmation - I'm not sure about that one, as the modal close action is controlled by Wicket I might need @steveswinsburg to help with this one.  Perhaps we can create a separate issue for this requirement?

**Comment by steveswinsburg** [comment] 2015-08-22 23:48
I am pretty sure we can open another window on closing, however the
original window would be closed, I dont think we could hook all of the
callbacks in. The simplest way would just be a standard javascript confirm
though.
The other option is to just use one modal for it all, and completely
replace the contents of the first modal window with a confirmation screen,
and then if they click OK, then close it, otherwise load the first panel
contents back in.

**Comment by kyleblythe** [comment] 2015-08-27 21:42
Hi @payten ,

Just to clarify on where the weight column would appear - GB1 displays it after the "Grade" column:

http://www.screencast.com/t/0XtNHXUjfC

And yes, the items would display as blank, with a percentage appearing at the category-level.

**Comment by payten** [comment] 2015-08-28 00:26
PRs have been submitted for weight column and blur effect.

I've created a new issue as I don't think students have permission to access category score and weight data from the Gradebook service: #202.

**Comment by kyleblythe** [comment] 2015-09-03 17:52
Hi @payten ,

Looks absolutely fantastic. Love the blurring effect, the placement of the weight column, and the close confirmation. A few quick things:
- Looks like there's a little bit of visual weirdness occurring with the comments rows when in Student Review Mode:

![2015-09-03_13-42-59](https://cloud.githubusercontent.com/assets/11447474/9666116/3728af02-5242-11e5-92bd-2fb7836f205f.png)
- Can we change the language of the close confirmation dialog box to:
  Unreleased grades and other students' data will become visible.
- Additionally, it currently looks like the close confirmation appears when a) clicking the "Done" button, and b) selecting the "x" icon in the upper right. Would it be possible to also have it appear when we click the "Grade Summary" link to go back into the instructor review mode? For this particular case, when clicking "Continue" on the confirmation message, you would be taken back to "Grade Summary" screen for that student, rather than the main spreadsheet.

**Comment by kyleblythe** [comment] 2015-09-17 15:35
Confirmed!

**Closed as completed by kyleblythe** 2015-09-17 15:35 UTC
Labels: enhancement, ready to test
