### ISSUE TITLE
Reordering column - updated scores not reflecting

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#70] opened 2015-05-07 21:25 UTC
When a column is drag-n-dropped, only the first row reflects the new ordering. Rows 2+ remain fixed, showing the scores for the existing item placement.

Ordering does not appear to save either.

**Comment by payten** [comment] 2015-05-07 22:13
Ah yep.. the first issue is a bug in the drag and drop javascript.  The plugin we use for dragging columns doesn't support having hidden columns so I had to get creative and a little bit hacky.  I'll look into implementing our own drag and drop... that'll be fun :joy_cat: 

Regarding the save... will investigate further as it seems to be throwing an error:  https://gist.github.com/payten/df19bc1b904a7e3dc152

**Comment by payten** [comment] 2015-05-08 05:53
@steveswinsburg on Sandbox1 we're seeing the null pointer exception (in the gist above) deep in the gradebook service `org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.updateAssignmentOrder`.  I have a feeling it's because we've frozen the Sakai build version at commit `3b5cb7d63c8024e544a450eb09752e27a5573201` from `Sat Apr 18 07:48:23 2015 +1000`.  Do we need to upgrade Sakai on Sandbox1?  And I'm guessing we'll need to push on with Tomcat8 and Java8 too?

**Comment by payten** [comment] 2015-05-08 06:46
Hm I'm wrong... the latest Sakai build is throwing the same NPE.  I'll dig into it...

It looks like the grade items in `gb_gradable_object_t` all have a `sort_order` of null, hence the NPE on line 2785 of `GradebookServiceHibernateImpl.java` - it all starts to play nice once I poke some integers in there.  Perhaps we need to set this order value on grade item creation?

**Comment by steveswinsburg** [comment] 2015-05-11 08:57
This method is one I wrote, it was working previously, I wondering if
something recent has changed it/caused a regression. I haven't updated
trunk yet as I haven't had a chance to upgrade Java/Tomcat. I can certainly
fix this one if you haven't found the issue already.

**Comment by steveswinsburg** [comment] 2015-05-12 12:23
Ok I've found the problem and will be pushing a fix up shortly.

**Comment by steveswinsburg** [comment] 2015-05-12 12:42
Hey @Payten, I have found a bug that appears to be in the JS relating to this. It seems to be always sending the same assignment Id for updating the order. I had a look at the network requests in the browser and this appears to be the case. I've fixed the backend bug, it should be merged shortly.

**Comment by payten** [comment] 2015-05-18 04:19
Just investigating the "same assignment ID" issue and I'm not seeing it happen in the latest version.  I'm wondering if my refactor of the drag and drop code fixed it? I'll take it! :trophy:

**Closed as completed** 2015-05-19 11:55 UTC
Labels: bug
